spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  datasource:
    drive-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/spring-boot
    password: Hima@63546
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Welcome from application.properties

management:
  endpoints:
    web:
      exposure:
        include: "*"

---

spring:
  profiles: test
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:mem:dcbapp
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true